wget wwtweb.blob.core.windows.net/docs/images/AcademicKit.jpg
wget wwtweb.blob.core.windows.net/docs/images/StudyChoppedDialog.jpg
wget wwtweb.blob.core.windows.net/docs/images/Saturn.png
wget wwtweb.blob.core.windows.net/docs/images/SaturnChopped.jpg
wget wwtweb.blob.core.windows.net/docs/uiimages/ImageAlignment.jpg
wget wwtweb.blob.core.windows.net/docs/images/ToastInput1.bmp
wget wwtweb.blob.core.windows.net/docs/images/ToastWtml.jpg
wget wwtweb.blob.core.windows.net/docs/images/ToastOutput1.bmp
wget wwtweb.blob.core.windows.net/docs/images/ToastTest.bmp
wget wwtweb.blob.core.windows.net/docs/images/ToastLR.bmp
wget wwtweb.blob.core.windows.net/docs/images/ToastRL.bmp
wget wwtweb.blob.core.windows.net/docs/images/ToastGalactic.bmp
wget wwtweb.blob.core.windows.net/docs/images/Toast45.bmp
wget wwtweb.blob.core.windows.net/docs/images/ToastPanorama.bmp
wget wwtweb.blob.core.windows.net/docs/images/ToastPanorama2.bmp
wget wwtweb.blob.core.windows.net/docs/images/PanoramaInput.bmp
wget wwtweb.blob.core.windows.net/docs/images/FillOption.bmp
wget wwtweb.blob.core.windows.net/docs/images/PanoramaNoFill.bmp
wget wwtweb.blob.core.windows.net/docs/images/PanoramaExtendTopRow.bmp
wget wwtweb.blob.core.windows.net/docs/images/PanoramaAverageOfTopRow.bmp
wget wwtweb.blob.core.windows.net/docs/images/PanoramaZoneGrey.bmp
